name: Generate Redirect Pages

on:
  push:
    branches:
      - main  # You can change this to your default branch

jobs:
  generate-redirect-pages:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run generateRedirectPages script
      run: node generateRedirectPages.js

    - name: Commit and push changes
      run: |
        git config --global user.name "ritikpatidar9803"
        git config --global user.email "ritikpatidar9803.com"
        git add .
        git commit -m "Automated redirect page generation"
        git push
